<a href="https://colab.research.google.com/github/kne160/Test/blob/master/CW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import argparse
import configparser

def train(config):
    print(config)

def test(config):
    parser = configparser.ConfigParser()
    parser.sections()
    parser.read(config)

    keys = parser.keys()
    for key in keys:
        print(key)

    path_train = parser["PATH"]["path_train"]
    print(path_train)


def main():

    parser = argparse.ArgumentParser(description='Coursework 1')

    parser.add_argument('--config', type=str, required=True, help='Configuration file')
    parser.add_argument('--train', action='store_true', help='Training mode - model is saved')
    parser.add_argument('--test', action='store_true', help='Testing mode - needs a model to load')

    args = parser.parse_args()

    if args.train:
        # call train function
        train(args.config)
    elif args.test:
        # call test function
        test(args.config)

if __name__ == '__main__':
    main()


usage: ipykernel_launcher.py [-h] --config CONFIG [--train] [--test]
ipykernel_launcher.py: error: the following arguments are required: --config


SystemExit: ignored

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2890: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [ ]:
# python3 question_classifier.py --train --config [configuration_file_path] 
# python3 question_classifier.py --test --config [configuration_file_path]

#!python3 question_classifier.py --train --config config.ini
!python3 question_classifier.py --test --config config.ini

DEFAULT
PATH
MODEL
HP
../data/train.txt


In [ ]:
import torch

new_tensor = torch.Tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(new_tensor[2, :])
print(new_tensor.type())
print(new_tensor.shape)
print(new_tensor.dim())

print(new_tensor.view(-1, 9))

print(new_tensor.t())
print(new_tensor.permute(-1,0))

t1 = torch.randn(3, 3)
t2 = torch.randn(3, 3)

print(t1)
print(t2)
print(t1.cross(t2))
print(t1.mm(t2))
print(t1.mul(t2))

tensor([7., 8., 9.])
torch.FloatTensor
torch.Size([3, 3])
2
tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
tensor([[1., 4., 7.],
        [2., 5., 8.],
        [3., 6., 9.]])
tensor([[1., 4., 7.],
        [2., 5., 8.],
        [3., 6., 9.]])
tensor([[ 0.4638,  0.0204,  1.3965],
        [ 0.0432, -0.5977, -0.0860],
        [ 2.3171, -0.1520, -0.5210]])
tensor([[-0.0092,  2.0074,  1.2291],
        [-0.5345, -1.5776, -0.7481],
        [ 0.9889, -0.7280, -0.8977]])
tensor([[ 1.2811,  0.1953, -0.3126],
        [-0.4800, -0.2904,  0.6132],
        [-0.2475,  1.1677, -0.9391]])
tensor([[ 1.3659, -0.1178, -0.6988],
        [ 0.2340,  1.0923,  0.5775],
        [-0.4553,  5.2706,  3.4294]])
tensor([[-0.0043,  0.0410,  1.7165],
        [-0.0231,  0.9430,  0.0644],
        [ 2.2914,  0.1107,  0.4677]])


In [ ]:
x = torch.ones(1, requires_grad=True)
y = x + 2
z = y * y * 2 # (dz / dx = 4 * y)

z.backward()
print(x.grad)

tensor([12.])


In [ ]:
import torch.nn as nn
lstm = nn.LSTM(3,3)

inputs = [torch.randn(1, 3) for _ in range(5)]
inputs_t = torch.cat(inputs).view(len(inputs), 1, -1)

print(inputs_t.shape)

hidden = (torch.randn(1,1,3), torch.randn(1,1,3))

out, hidden = lstm(inputs_t, hidden)

print(out)

print(hidden)

torch.Size([5, 1, 3])
tensor([[[ 0.1596, -0.5134, -0.2547]],

        [[ 0.2183, -0.2402, -0.0764]],

        [[ 0.0143,  0.0333,  0.0173]],

        [[-0.1370,  0.1361,  0.0078]],

        [[-0.1780,  0.1867,  0.1202]]], grad_fn=<StackBackward>)
(tensor([[[-0.1780,  0.1867,  0.1202]]], grad_fn=<StackBackward>), tensor([[[-0.3085,  0.3659,  0.2604]]], grad_fn=<StackBackward>))


In [2]:
!git clone https://gitlab.cs.man.ac.uk/r53375ks/test.git

Cloning into 'test'...
fatal: could not read Username for 'https://gitlab.cs.man.ac.uk': No such device or address
